#!/bin/sh
#
# $FreeBSD: releng/11.1/etc/rc.d/automountd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: automountd
# REQUIRE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="automountd"
desc="daemon handling autofs mount requests"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_modules="autofs"

load_rc_config $name
run_rc_command "$1"
