#!/bin/sh
#
# $FreeBSD: releng/11.0/etc/rc.d/autounmountd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: autounmountd
# REQUIRE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="autounmountd"
desc="daemon unmounting automounted filesystems"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
