#!/bin/sh
#
# $FreeBSD: releng/11.1/etc/rc.d/rarpd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: rarpd
# REQUIRE: DAEMON FILESYSTEMS
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="rarpd"
desc="Reverse ARP daemon"
rcvar="rarpd_enable"
command="/usr/sbin/${name}"
required_files="/etc/ethers"

load_rc_config $name
pidfile="${rarpd_pidfile:-/var/run/${name}.pid}"

run_rc_command "$1"
