#!/bin/sh
#
# $FreeBSD: releng/11.0/etc/rc.d/swaplate 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: swaplate
# REQUIRE: mountlate
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swaplate"
desc="Setup late swap space"
start_cmd='/sbin/swapon -aLq'
stop_cmd='/sbin/swapoff -aq'

load_rc_config swap
run_rc_command "$1"
